const quotes = [
    "Believe you can and you're halfway there.",
    "The only way to do great work is to love what you do.",
    "Don't watch the clock; do what it does. Keep going.",
    "The future depends on what you do today.",
    "Success is not in what you have, but who you are.",
    "Push yourself, because no one else is going to do it for you.",
    "Success doesn’t come from what you do occasionally. It comes from what you do consistently.",
    "Believe in yourself and all that you are.",
    "Dream it. Wish it. Do it.",
    "Sometimes later becomes never. Do it now.",
    "Don’t wait for opportunity. Create it.",
    "Great things never come from comfort zones.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Little things make big days.",
    "It always seems impossible until it's done.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "If you can dream it, you can do it.",
    "Hard work beats talent when talent doesn’t work hard.",
    "Success is what happens after you’ve survived all your mistakes.",
    "Don’t be afraid to give up the good to go for the great.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Do something today that your future self will thank you for.",
    "Discipline is doing what needs to be done, even if you don’t want to do it.",
    "Act as if what you do makes a difference. It does.",
    "Quality is not an act, it is a habit.",
    "Either you run the day or the day runs you.",
    "With the new day comes new strength and new thoughts.",
    "Optimism is the faith that leads to achievement.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "Set your goals high, and don’t stop till you get there.",
    "Don’t limit your challenges. Challenge your limits.",
    "Failure will never overtake me if my determination to succeed is strong enough.",
    "Go as far as you can see; when you get there, you’ll be able to see further.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Do not wait to strike till the iron is hot, but make it hot by striking.",
    "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
    "Keep your face always toward the sunshine—and shadows will fall behind you.",
    "The best revenge is massive success.",
    "You are never too old to set another goal or to dream a new dream.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "Your time is limited, so don’t waste it living someone else’s life.",
    "The best way to get started is to quit talking and begin doing.",
    "It’s not whether you get knocked down, it’s whether you get up.",
    "If you are working on something exciting, it will keep you motivated.",
    "People who are crazy enough to think they can change the world, are the ones who do.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Creativity is intelligence having fun.",
    "Failure is the opportunity to begin again more intelligently.",
    "What seems to us as bitter trials are often blessings in disguise.",
    "Action is the foundational key to all success.",
    "There is no substitute for hard work.",
    "Try not to become a man of success, but rather try to become a man of value.",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "A goal is a dream with a deadline.",
    "You miss 100% of the shots you don’t take.",
    "You only live once, but if you do it right, once is enough.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "Never regret anything that made you smile.",
    "Hustle in silence and let your success make the noise.",
    "Don’t wish for it. Work for it.",
    "Make each day your masterpiece.",
    "You were born to be a player. You were meant to be here.",
    "Don’t count the days, make the days count.",
    "Doubt kills more dreams than failure ever will.",
    "Turn your wounds into wisdom.",
    "Opportunities don’t happen. You create them.",
    "Don't limit yourself. You can go as far as your mind lets you.",
    "Learn as if you will live forever, live like you will die tomorrow.",
    "The purpose of our lives is to be happy.",
    "Be so good they can’t ignore you.",
    "You don’t need to see the whole staircase, just take the first step.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "If you really look closely, most overnight successes took a long time.",
    "Motivation gets you going, but discipline keeps you growing.",
    "Success is not just about making money. It’s about making a difference.",
    "Energy and persistence conquer all things.",
    "Don’t raise your voice, improve your argument.",
    "The best way out is always through.",
    "Do what you can with all you have, wherever you are.",
    "Believe in the possibility of what you plan.",
    "Don’t let yesterday take up too much of today.",
    "Success is falling nine times and getting up ten.",
    "Winners never quit and quitters never win.",
    "When one door closes, another opens.",
    "Never stop learning because life never stops teaching.",
    "Difficult roads often lead to beautiful destinations.",
    "The man who moves a mountain begins by carrying away small stones.",
    "It always seems impossible until it's done.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "Start where you are. Use what you have. Do what you can.",
    "Dream big and dare to fail.",
    "Don’t let what you cannot do interfere with what you can do.",
    "Be the change that you wish to see in the world.",
    "Sometimes you win, sometimes you learn.",
    "Don’t count the days, make the days count.",
    "The only person you are destined to become is the person you decide to be.",
    "Perseverance is not a long race; it is many short races one after the other.",
    "Everything you can imagine is real.",
    "You become what you believe.",
    "Be fearless in the pursuit of what sets your soul on fire.",
    "Success means doing the best we can with what we have."
  ];
  

  const quote = document.getElementById('quote');

  const button = document.getElementById('btn');

  function randomOuate(){
   let ans = Math.floor(Math.random() * quotes.length)
   quote.innerHTML = quotes[ans];
  }

 button.addEventListener("click", randomOuate );


